# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voting_pb2 as voting__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VotingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Vote = channel.unary_unary(
                '/VotingService/Vote',
                request_serializer=voting__pb2.VoteRequest.SerializeToString,
                response_deserializer=voting__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.GetResults = channel.unary_unary(
                '/VotingService/GetResults',
                request_serializer=voting__pb2.Empty.SerializeToString,
                response_deserializer=voting__pb2.ResultsResponse.FromString,
                _registered_method=True)
        self.GetCandidates = channel.unary_unary(
                '/VotingService/GetCandidates',
                request_serializer=voting__pb2.Empty.SerializeToString,
                response_deserializer=voting__pb2.CandidateList.FromString,
                _registered_method=True)


class VotingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VotingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=voting__pb2.VoteRequest.FromString,
                    response_serializer=voting__pb2.VoteResponse.SerializeToString,
            ),
            'GetResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResults,
                    request_deserializer=voting__pb2.Empty.FromString,
                    response_serializer=voting__pb2.ResultsResponse.SerializeToString,
            ),
            'GetCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandidates,
                    request_deserializer=voting__pb2.Empty.FromString,
                    response_serializer=voting__pb2.CandidateList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VotingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VotingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VotingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VotingService/Vote',
            voting__pb2.VoteRequest.SerializeToString,
            voting__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VotingService/GetResults',
            voting__pb2.Empty.SerializeToString,
            voting__pb2.ResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VotingService/GetCandidates',
            voting__pb2.Empty.SerializeToString,
            voting__pb2.CandidateList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
