# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voting.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'voting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvoting.proto\"#\n\x0bVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\"\x1f\n\x0cVoteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"4\n\x0fResultsResponse\x12!\n\x07results\x18\x01 \x03(\x0b\x32\x10.CandidateResult\"D\n\x0f\x43\x61ndidateResult\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\x12\r\n\x05votes\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"%\n\tCandidate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"/\n\rCandidateList\x12\x1e\n\ncandidates\x18\x01 \x03(\x0b\x32\n.Candidate2\x85\x01\n\rVotingService\x12#\n\x04Vote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12&\n\nGetResults\x12\x06.Empty\x1a\x10.ResultsResponse\x12\'\n\rGetCandidates\x12\x06.Empty\x1a\x0e.CandidateListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=16
  _globals['_VOTEREQUEST']._serialized_end=51
  _globals['_VOTERESPONSE']._serialized_start=53
  _globals['_VOTERESPONSE']._serialized_end=84
  _globals['_EMPTY']._serialized_start=86
  _globals['_EMPTY']._serialized_end=93
  _globals['_RESULTSRESPONSE']._serialized_start=95
  _globals['_RESULTSRESPONSE']._serialized_end=147
  _globals['_CANDIDATERESULT']._serialized_start=149
  _globals['_CANDIDATERESULT']._serialized_end=217
  _globals['_CANDIDATE']._serialized_start=219
  _globals['_CANDIDATE']._serialized_end=256
  _globals['_CANDIDATELIST']._serialized_start=258
  _globals['_CANDIDATELIST']._serialized_end=305
  _globals['_VOTINGSERVICE']._serialized_start=308
  _globals['_VOTINGSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
